issue:
  provider: 
branch:
  pattern: "{{.Type}}\\/({{.Parent}}-)?{{.Description}}" # Branch name pattern
  variable_patterns: # A map of patterns to match for each template variable
    Type: "fix|feat|chore|docs|refactor|test|style|build|ci|perf|revert"
    Parent: "S-[0-9]+"
    Description: "[a-z_]*"
  token_separators: ["_"] # Characters used to separate branch name into a human-readable string
pr:
  title: "{{.Type}}{{with .Parent}}({{.}}){{end}}: {{humanize .Description}}"
